/* Main.c file generated by New Project wizard
 *
 * Created:   sá. oct. 17 2020
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include "config.h"

#define _XTAL_FREQ 8000000

#define PINA0 PORTAbits.RA0
#define PINA1 PORTAbits.RA1
#define PINA2 PORTAbits.RA2
#define PINA3 PORTAbits.RA3
#define PIND7 PORTDbits.RD7
#define PINC1 PORTCbits.RC1
#define tP1 150
#define tP2 5


void configPIC(){
   //config PIC
   ANSELA = 0x00;  // All pins as digital
   ANSELC = 0x00;  // All pins as digital
   ANSELD = 0x00;  // All pins as digital

   TRISA = 0x00;   // Output
   TRISC = 0x02;   // Input
   TRISD = 0x00;   // Output
}

void displayValue(int display, int value, int decimal) {
   if (display == 0) PINA0 = 1;
   else if (display == 1) PINA1 = 1;
   else if (display == 2) PINA2 = 1;
   else if (display == 3) PINA3 = 1;
   
   if (value == 0) PORTD = 0x3F;
   else if (value == 1) PORTD = 0x06;
   else if (value == 2) PORTD = 0x5B;
   else if (value == 3) PORTD = 0x4F;
   else if (value == 4) PORTD = 0x66;
   else if (value == 5) PORTD = 0x6D;
   else if (value == 6) PORTD = 0x7D;
   else if (value == 7) PORTD = 0x07;
   else if (value == 8) PORTD = 0x7F;
   else if (value == 9) PORTD = 0x6F;
      
   if (decimal == 1) PIND7 = 1;
   __delay_ms(tP2);
}

void func(int val, int dec) {
   for (int i = 0; i < 4; i++) {
      if (i == dec) displayValue(i, val % 10, 1);
      else displayValue(i, val % 10, 0);
      PORTA = 0x00;
      val = val / 10;
   }
}

void programa2() {
   PORTA = 0x00;
   func(267, 2);
}

void programa1() {
   PORTA = 0x02;
   for (int i = 0; i < 10 && PINC1 == 1; i++) {
      if (i == 0) PORTD = 0x3F;
      else if (i == 1) PORTD = 0x06;
      else if (i == 2) PORTD = 0x5B;
      else if (i == 3) PORTD = 0x4F;
      else if (i == 4) PORTD = 0x66;
      else if (i == 5) PORTD = 0x6D;
      else if (i == 6) PORTD = 0x7D;
      else if (i == 7) PORTD = 0x07;
      else if (i == 8) PORTD = 0x7F;
      else if (i == 9) PORTD = 0x6F;
      __delay_ms(tP1);
   }
}

void main(void){
   configPIC();
   while(1) {
      if (PINC1 == 1) programa1();
      else programa2();
   }
}